Dog list cubit
k1mka/dog_list pull request #4
Opened 2022-08-10 18:19 UTC by k1mka

2022-08-10 18:42 UTC, zddarova requested changes

2022-08-10 18:42 UTC, zddarova commented on lib/data/services/get_it.dart
> +import 'package:array_names/data/repositories/repository.dart';
move to lib and dont delete get it

2022-08-10 18:42 UTC, zddarova commented on lib/presentation/screens/images_screen/images_screen.dart
> +      create: (context) => DogsImagesBloc(getIt<Repository>(), breed),
you could pass breed to the event instead of to bloc directly

2022-08-10 18:42 UTC, zddarova commented on lib/presentation/screens/images_screen/images_screen_layout.dart
> +    context.read<DogsImagesBloc>().add(LoadingImagesEvent());
as i said, you could pass breed to event here, instead of passing it to bloc

2022-08-10 18:42 UTC, zddarova commented on lib/presentation/screens/images_screen/images_screen_layout.dart
> +          return const Text('Ошибка загрузки фотографий');
you could use and configure widget for error that u use on dog list screen

2022-08-10 18:42 UTC, zddarova commented on lib/business_logic/cubit_states/events.dart
> +abstract class Events {}
refactor as we disscuss

2022-08-10 18:44 UTC, zddarova commented on lib/business_logic/cubit_states/events.dart
> +abstract class Events {}
and name events as a verb (glagol)

2022-08-12 10:22 UTC, k1mka commented on lib/business_logic/cubit_states/events.dart
> +abstract class Events {}
discussed*

2022-08-16 05:38 UTC, zddarova approved these changes

2022-08-16 05:38 UTC, merged